# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortid', models.CharField(max_length=6)),
                ('fullMobileUrl', models.CharField(max_length=500)),
                ('fullDesktopUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
