# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='fullTabletUrl',
            field=models.CharField(default='t.google.com', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='fullDesktopUrl',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='fullMobileUrl',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='shortid',
            field=models.CharField(max_length=10),
        ),
    ]
