# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0002_auto_20160627_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 28, 1, 51, 55, 230000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='hitCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
