# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0003_auto_20160627_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='hitCount',
            new_name='desktopRedirectCount',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='mobileRedirectCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='tabletRedirectCount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
