# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorty', '0005_auto_20160627_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='shortid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
